---
- name: First Play - Docker Image Build
  hosts: 192.168.1.13
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansible/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansible
    - name : Build image
      command: docker build -t 562100/mavenwebapp .
    - name : Push Docker Image
      command: docker push 562100/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deploy.yml
       dest: /home/ansible
   - name : K8S Deployment
     command: kubectl apply -f k8s-deploy.yml
